<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>038-async函数的await,html</title>
</head>
<body>
	
</body>
<script>
	
	async function fn(){
		// await只能放到async函数体中
		// await表示后面的处理需要等待,通常await后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。
		let data1 = await 'hello';
		// let data1 = 'hello';

		console.log(data1);
	}
	fn();
	*/

	let promise = new Promise((resolve,reject)=>{
		setTimeout(()=>{
			resolve('进行中。。');
		},200)
	});

	// await表示后面的处理需要等待,通常await后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。
	/*
	async function fn(){
		let data1 = await promise;
		console.log(data1);
	}
	fn();
	*/
	/*
	async function fn(){
		await Promise.reject('失败了..');
		//后面的程序不被执行
		let data1 = await promise;
		console.log(data1);
	}
	fn()
	.catch(err=>{
		console.log("reject:",err);
	})
	*/
	async function fn(){
		try{
			await Promise.reject('失败了..');
		}
		catch(err){
			console.log("reject1:",err);
		}

		try{
			let data1 = await promise;
			console.log(data1);
		}
		catch(err){
			console.log("reject2:",err);
		}
	}
	fn();
</script>
</html>